logging:
    file:
        name: log/sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info
# JWT 설정
# - secret Key는 HS256 알고리즘으로 암호화/복호화를 하기 위해 256비트보다 커야됨
# - 영문자 하나의 알파벳은 8비트(1바이트)이므로 32글자 이상이면 됨
# - https://randomkeygen.com/
# - https://acte.ltd/utils/randomkeygen
server:
    port: 8080
    servlet:
        context-path: /sboard
spring:
    application:
        name: sboard
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Asdf!2#4
        url: jdbc:mysql://127.0.0.1:3306/jboard
        username: jo9uu
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false



# 이메일 설정
    mail:
        host: smtp.gmail.com
        port: 587
        username: sardia0923@gmail.com
        password: kjqj swio ysab mvlu
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
    thymeleaf:
        prefix: classpath:/templates



mybatis:
    mapper-locations: classpath:mappers/**/*.xml

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    servlet:
        mulitpart:
            location: uploads/
            max-file-size: 10mb

# 파일 업로드 설정
file:
    upload:
        path: uploads/



